services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8383:8383"
    volumes:
      - .:/app
      - .env:/app/.env
    env_file:
      - .env
